apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/food-lover-default: "true"
        io.kompose.service: mongo
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/acmeair-g12/fdmongo
          name: mongo
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
          resources: {}
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-claim0 # 这里替换成您的 PVC 名称
      restartPolicy: Always
status: {}
